package com.cuit.springboot.gdao;

import com.cuit.springboot.gentry.Sysmsg;
import java.util.List;

public interface SysmsgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysmsg
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysmsg
     *
     * @mbggenerated
     */
    int insert(Sysmsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysmsg
     *
     * @mbggenerated
     */
    Sysmsg selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysmsg
     *
     * @mbggenerated
     */
    List<Sysmsg> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysmsg
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Sysmsg record);
}